# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
description:      Quantitative virus ecology course material

github:
  repo:           https://github.com/dtalmy/dtalmy.github.io

baseurl:          /
paginate:         5

paginate_path:       "page:num"

plugins:
  - jekyll-gist
  - jekyll-paginate
